import { Platform, StyleSheet } from 'react-native';
import { colors } from '../../theme';

export const setupStyles = StyleSheet.create({
  setupModalRoot: { flex: 1, justifyContent: 'flex-end' },
  setupSheet: {
    maxHeight: '88%',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: colors.surface,
  },
  setupSheetContent: {
    paddingHorizontal: 22,
    paddingBottom: Platform.OS === 'ios' ? 34 : 24,
  },
  setupSheetHeading: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 4,
  },
  setupLoading: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.canvas,
  },
  setupScreen: {
    flex: 1,
    backgroundColor: colors.canvas,
    justifyContent: 'center',
    paddingHorizontal: 22,
    paddingVertical: 24,
  },
  setupCard: {
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 26,
    padding: 24,
  },
  setupIcon: {
    width: 54,
    height: 54,
    borderRadius: 18,
    backgroundColor: '#F0E6F4',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
  },
  setupEyebrow: { color: colors.accent, fontSize: 11, fontWeight: '800', letterSpacing: 1.4 },
  setupTitle: {
    color: colors.ink,
    fontSize: 28,
    fontWeight: '800',
    letterSpacing: -0.6,
    marginTop: 6,
  },
  setupIntro: { color: colors.muted, fontSize: 13, lineHeight: 19, marginTop: 9, marginBottom: 22 },
  setupLabel: {
    color: colors.ink,
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 7,
    marginTop: 13,
  },
  setupInput: {
    height: 50,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 14,
    backgroundColor: colors.canvas,
    paddingHorizontal: 14,
    color: colors.ink,
    fontSize: 14,
  },
  setupTokenField: {
    height: 50,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 14,
    backgroundColor: colors.canvas,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
  },
  setupTokenInput: { flex: 1, color: colors.ink, fontSize: 14, marginRight: 10 },
  setupError: { color: '#B42318', fontSize: 12, lineHeight: 17, marginTop: 12 },
  setupRecovery: {
    borderWidth: 1,
    borderColor: '#F2C7C2',
    borderRadius: 13,
    backgroundColor: '#FFF4F2',
    padding: 12,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 9,
    marginBottom: 8,
  },
  setupRecoveryText: { flex: 1, color: '#8A271F', fontSize: 12, lineHeight: 18 },
  setupActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10, marginTop: 24 },
  setupCancel: { minHeight: 48, justifyContent: 'center', paddingHorizontal: 17 },
  setupCancelText: { color: colors.ink, fontSize: 14, fontWeight: '700' },
  setupSave: {
    minHeight: 48,
    borderRadius: 14,
    backgroundColor: colors.accent,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
  },
  setupSaveText: { color: colors.white, fontSize: 14, fontWeight: '800' },
});
