import { Platform, StyleSheet } from 'react-native';

import { colors } from './theme';

export const styles = StyleSheet.create({
  swipeProvider: { flex: 1 },
  safeArea: { flex: 1, backgroundColor: colors.canvas },
  appShell: { flex: 1, width: '100%', maxWidth: 760, alignSelf: 'center' },
  tabContent: { flex: 1 },
  content: { paddingHorizontal: 22, paddingTop: 24, paddingBottom: 120 },
  swipeContainer: {
    overflow: 'hidden',
    backgroundColor: '#D84A4A',
    borderRadius: 17,
  },
  borderedSwipeContainer: { borderWidth: 1, borderColor: colors.line },
  openSwipeContainer: { zIndex: 2 },
  swipeForeground: { backgroundColor: colors.canvas },
  borderedSwipeForeground: { backgroundColor: colors.surface },
  swipeDeleteButton: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    width: 82,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
  },
  swipeRevealSpacer: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    backgroundColor: colors.canvas,
  },
  swipeDeleteText: { color: colors.white, fontSize: 10, fontWeight: '800' },
  deleteConfirmBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(38, 31, 42, 0.55)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 28,
  },
  deleteConfirmCard: {
    width: '100%',
    maxWidth: 380,
    borderRadius: 24,
    backgroundColor: colors.surface,
    padding: 24,
    alignItems: 'center',
  },
  deleteConfirmIcon: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#FBE8E8',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  deleteConfirmTitle: { color: colors.ink, fontSize: 19, fontWeight: '800', textAlign: 'center' },
  deleteConfirmText: { color: colors.muted, fontSize: 13, marginTop: 8 },
  deleteConfirmActions: { flexDirection: 'row', gap: 10, marginTop: 24 },
  deleteCancelButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 14,
    backgroundColor: colors.canvas,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteCancelText: { color: colors.ink, fontSize: 14, fontWeight: '800' },
  deleteConfirmButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 14,
    backgroundColor: '#D84A4A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteConfirmButtonText: { color: colors.white, fontSize: 14, fontWeight: '800' },
  loadingMore: { marginVertical: 22 },
  summaryCard: {
    backgroundColor: colors.ink,
    borderRadius: 25,
    padding: 24,
    marginBottom: 30,
    shadowColor: '#3D2946',
    shadowOffset: { width: 0, height: 9 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 6,
  },
  eyebrow: { color: '#B8B9B1', fontSize: 11, letterSpacing: 1.4, fontWeight: '700' },
  balance: {
    color: colors.white,
    fontSize: 33,
    fontWeight: '700',
    marginTop: 8,
    letterSpacing: -1,
  },
  summaryDivider: { height: 1, backgroundColor: '#644D6D', marginVertical: 20 },
  summaryRow: { flexDirection: 'row', gap: 38 },
  summaryMetric: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  dot: { width: 9, height: 9, borderRadius: 5 },
  incomeDot: { backgroundColor: '#71C69E' },
  spentDot: { backgroundColor: '#C994E0' },
  metricLabel: { color: '#AEB0A8', fontSize: 12 },
  metricValue: { color: colors.white, fontSize: 15, fontWeight: '600', marginTop: 2 },
  listHeading: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  sectionTitle: { color: colors.ink, fontSize: 19, fontWeight: '700' },
  filterText: { color: colors.muted, fontSize: 13, fontWeight: '600' },
  queuePanel: {
    borderWidth: 1,
    borderColor: '#D8C4E1',
    borderRadius: 18,
    backgroundColor: '#F8F2FA',
    padding: 15,
    marginBottom: 24,
  },
  queueHeading: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  queueHeadingCopy: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  queueStatusDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.accent },
  queueTitle: { color: colors.ink, fontSize: 15, fontWeight: '800' },
  queueCount: {
    minWidth: 25,
    height: 25,
    borderRadius: 13,
    backgroundColor: '#EADCF0',
    color: colors.accentDark,
    textAlign: 'center',
    lineHeight: 25,
    fontSize: 12,
    fontWeight: '800',
  },
  queueIntro: { color: colors.muted, fontSize: 11, lineHeight: 16, marginTop: 6 },
  queueItem: {
    flexDirection: 'row',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#E5D7EA',
    marginTop: 13,
    paddingTop: 13,
  },
  queueItemIcon: {
    width: 38,
    height: 38,
    borderRadius: 13,
    backgroundColor: '#EADCF0',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  queueItemCopy: { flex: 1 },
  queueItemTitle: { color: colors.ink, fontSize: 13, fontWeight: '800' },
  queueItemMeta: { color: colors.muted, fontSize: 11, marginTop: 2 },
  queueItemError: { color: colors.accentDark, fontSize: 10, lineHeight: 15, marginTop: 5 },
  queueItemAction: { alignItems: 'flex-end', marginLeft: 8 },
  queueItemAmount: { color: colors.ink, fontSize: 12, fontWeight: '800' },
  retryQueueButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    minHeight: 28,
    paddingHorizontal: 8,
    marginTop: 4,
    borderRadius: 8,
    backgroundColor: colors.white,
  },
  retryQueueText: { color: colors.accent, fontSize: 11, fontWeight: '800' },
  discardQueueButton: { minHeight: 24, justifyContent: 'center', marginTop: 2 },
  discardQueueText: { color: colors.muted, fontSize: 10, fontWeight: '700' },
  transactionRow: {
    minHeight: 82,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
  },
  transactionIcon: {
    width: 45,
    height: 45,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 13,
  },
  expenseIcon: { backgroundColor: '#EFE5F3' },
  incomeIcon: { backgroundColor: '#DDF0E5' },
  transactionCopy: { flex: 1 },
  merchant: { color: colors.ink, fontSize: 15, fontWeight: '700' },
  transactionMeta: { color: colors.muted, fontSize: 12, marginTop: 4 },
  dateSectionHeader: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: '800',
    paddingTop: 20,
    paddingBottom: 10,
  },
  amount: { color: colors.ink, fontSize: 14, fontWeight: '700', marginLeft: 8 },
  incomeAmount: { color: colors.green },
  separator: { height: 1, backgroundColor: colors.line, marginLeft: 58 },
  fab: {
    position: 'absolute',
    right: 24,
    bottom: 28,
    width: 62,
    height: 62,
    borderRadius: 31,
    backgroundColor: colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.accentDark,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 13,
    elevation: 9,
  },
  fabPressed: { transform: [{ scale: 0.96 }], backgroundColor: colors.accentDark },
  state: { flex: 1, padding: 32, alignItems: 'center', justifyContent: 'center' },
  stateTitle: { color: colors.ink, fontSize: 20, fontWeight: '700', marginTop: 16 },
  stateText: { color: colors.muted, textAlign: 'center', lineHeight: 20, marginTop: 9 },
  retryButton: {
    backgroundColor: colors.ink,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
    marginTop: 20,
  },
  retryText: { color: colors.white, fontWeight: '700' },
  inlineError: { backgroundColor: '#F0E6F4', borderRadius: 12, padding: 12, marginBottom: 18 },
  inlineErrorText: { color: colors.accentDark, fontSize: 12 },
  emptyText: { color: colors.muted, textAlign: 'center', padding: 40 },
  modalRoot: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: colors.surface,
  },
  scrim: {
    position: 'absolute',
    top: 0,
    right: 0,
    left: 0,
    height: '16%',
    backgroundColor: colors.overlay,
  },
  sheet: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    height: '92%',
    paddingHorizontal: 22,
    paddingBottom: Platform.OS === 'ios' ? 28 : 22,
  },
  handle: {
    width: 42,
    height: 5,
    backgroundColor: '#D3CEC4',
    borderRadius: 4,
    alignSelf: 'center',
    marginTop: 10,
    marginBottom: 17,
  },
  sheetHeading: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  sheetTitleGroup: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  sheetTitleIcon: {
    width: 38,
    height: 38,
    borderRadius: 13,
    backgroundColor: '#F0E6F4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetTitle: { color: colors.ink, fontSize: 22, fontWeight: '800', letterSpacing: -0.4 },
  sheetHeadingActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  closeButton: {
    width: 39,
    height: 39,
    borderRadius: 20,
    backgroundColor: colors.canvas,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modeToggle: {
    backgroundColor: colors.canvas,
    borderRadius: 12,
    padding: 3,
    flexDirection: 'row',
    gap: 2,
  },
  modeButton: {
    width: 38,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
  },
  activeModeButton: { backgroundColor: colors.accent },
  form: { paddingBottom: 12 },
  fieldGroup: {
    marginBottom: 14,
  },
  fieldControl: { width: '100%' },
  choiceControl: { width: '100%', flexDirection: 'row', alignItems: 'center', gap: 9 },
  choiceScroller: { flex: 1 },
  choiceRow: { gap: 9, paddingRight: 10 },
  choice: {
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.white,
    paddingHorizontal: 15,
    minHeight: 40,
    justifyContent: 'center',
    borderRadius: 20,
  },
  activeChoice: { borderColor: colors.accent, backgroundColor: '#F0E6F4' },
  choiceText: { color: colors.muted, fontSize: 14, fontWeight: '600' },
  activeChoiceText: { color: colors.accentDark },
  tagSearchButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tagSearchSheet: {
    height: '68%',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    backgroundColor: colors.surface,
    paddingHorizontal: 18,
    paddingBottom: Platform.OS === 'ios' ? 28 : 18,
  },
  tagSearchHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  tagSearchField: {
    height: 52,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.canvas,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  tagSearchList: { gap: 10, paddingTop: 16, paddingBottom: 24 },
  tagSearchOption: {
    minHeight: 52,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  activeTagSearchOption: { borderColor: colors.accent, backgroundColor: '#FAF5FC' },
  tagCheckbox: {
    width: 24,
    height: 24,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.line,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeTagCheckbox: { borderColor: colors.accent, backgroundColor: colors.accent },
  tagSearchOptionText: { color: colors.ink, fontSize: 14, fontWeight: '700' },
  categoryField: {
    width: '100%',
    height: 50,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 14,
    backgroundColor: colors.white,
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  categoryFieldPressed: { backgroundColor: '#FAF8FB' },
  categoryFieldSelection: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 },
  categoryFieldIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F2EEF4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryFieldText: { color: colors.ink, fontSize: 14, fontWeight: '700' },
  categoryPlaceholder: { color: '#A7A0AA', fontSize: 14 },
  nestedModalRoot: { flex: 1, justifyContent: 'flex-end' },
  nestedScrim: {
    position: 'absolute',
    inset: 0,
    backgroundColor: 'rgba(42, 29, 48, 0.58)',
  },
  categorySheet: {
    height: '66%',
    backgroundColor: colors.surface,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 18,
    paddingBottom: Platform.OS === 'ios' ? 28 : 18,
    shadowColor: '#2A1D30',
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.18,
    shadowRadius: 24,
    elevation: 18,
  },
  categorySheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    marginBottom: 18,
  },
  categorySheetTitle: { color: colors.ink, fontSize: 22, fontWeight: '800' },
  categorySheetSubtitle: { color: colors.muted, fontSize: 12, marginTop: 4 },
  categoryGrid: { paddingBottom: 22 },
  categoryGridRow: { alignItems: 'flex-start' },
  categoryTile: { width: '33.333%', alignItems: 'center', paddingHorizontal: 5, marginBottom: 20 },
  categoryTileIcon: {
    width: 66,
    height: 66,
    borderRadius: 33,
    backgroundColor: '#F3F5F6',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  activeCategoryTileIcon: { borderColor: colors.accent, backgroundColor: '#F0E6F4' },
  categoryCheckBadge: {
    position: 'absolute',
    right: -2,
    top: -2,
    width: 21,
    height: 21,
    borderRadius: 11,
    backgroundColor: colors.accent,
    borderWidth: 2,
    borderColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryTileText: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 16,
    textAlign: 'center',
    marginTop: 8,
  },
  activeCategoryTileText: { color: colors.accentDark, fontWeight: '700' },
  categoryEmpty: { color: colors.muted, textAlign: 'center', paddingVertical: 40 },
  accountSheet: {
    maxHeight: '62%',
    backgroundColor: colors.surface,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 20,
    paddingBottom: Platform.OS === 'ios' ? 28 : 18,
  },
  accountOptions: { gap: 11, paddingTop: 20, paddingBottom: 10 },
  accountOption: {
    minHeight: 62,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
  },
  activeAccountOption: { borderColor: colors.accent, backgroundColor: '#F0E6F4' },
  accountOptionIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F2EEF4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  accountOptionText: { flex: 1, color: colors.ink, fontSize: 14, fontWeight: '600' },
  activeAccountOptionText: { color: colors.accentDark, fontWeight: '700' },
  field: {
    width: '100%',
    height: 50,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 13,
    backgroundColor: colors.white,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    gap: 11,
  },
  multilineField: { height: 80, alignItems: 'flex-start', paddingTop: 15 },
  input: { flex: 1, color: colors.ink, fontSize: 15, outlineStyle: 'none' } as never,
  multilineInput: { minHeight: 50, textAlignVertical: 'top' },
  dateShortcuts: { width: '100%' },
  dateCalendarButton: {
    minHeight: 48,
    width: '100%',
    minWidth: 0,
    paddingHorizontal: 13,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 9,
  },
  dateCalendarText: { color: colors.ink, fontSize: 14, fontWeight: '700' },
  webDateInput: { justifyContent: 'flex-start' },
  webDateTextInput: {
    flex: 1,
    color: colors.ink,
    fontSize: 14,
    fontWeight: '700',
    outlineStyle: 'none',
  } as never,
  datePickerSheet: {
    width: '100%',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    backgroundColor: colors.surface,
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 24,
  },
  datePickerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  dateDoneButton: {
    minHeight: 38,
    paddingHorizontal: 15,
    borderRadius: 12,
    backgroundColor: '#F0E6F4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dateDoneText: { color: colors.accentDark, fontSize: 13, fontWeight: '800' },
  datePicker: { width: '100%' },
  splitCard: {
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 16,
    padding: 15,
    marginBottom: 16,
    backgroundColor: '#FAF8FB',
  },
  splitTitle: { color: colors.ink, fontWeight: '700', marginBottom: 14 },
  errorText: {
    color: colors.accentDark,
    fontSize: 12,
    lineHeight: 18,
    marginBottom: 12,
    backgroundColor: '#F8EFFA',
    borderRadius: 10,
    padding: 10,
  },
  sheetActions: {
    borderTopWidth: 1,
    borderTopColor: colors.line,
    paddingTop: 15,
    flexDirection: 'row',
    gap: 12,
  },
  cancelButton: {
    minHeight: 49,
    paddingHorizontal: 22,
    borderRadius: 14,
    backgroundColor: colors.canvas,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelText: { color: colors.ink, fontWeight: '700', fontSize: 14 },
  saveButton: {
    flex: 1,
    minHeight: 49,
    borderRadius: 14,
    backgroundColor: colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  disabledButton: { opacity: 0.42 },
  saveText: { color: colors.white, fontWeight: '700', fontSize: 14 },
  bottomNavigation: {
    minHeight: 76,
    borderTopWidth: 1,
    borderTopColor: colors.line,
    backgroundColor: colors.surface,
    flexDirection: 'row',
    paddingHorizontal: 12,
    paddingTop: 8,
  },
  bottomTab: { flex: 1, alignItems: 'center', justifyContent: 'flex-start', gap: 3 },
  bottomTabIcon: {
    width: 42,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeBottomTabIcon: { backgroundColor: '#F0E6F4' },
  receiptBadge: {
    position: 'absolute',
    top: -5,
    right: -5,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    paddingHorizontal: 5,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.accent,
    borderWidth: 2,
    borderColor: colors.surface,
  },
  receiptBadgeText: { color: colors.white, fontSize: 9, fontWeight: '800' },
  bottomTabText: { color: colors.muted, fontSize: 11, fontWeight: '600' },
  activeBottomTabText: { color: colors.accentDark, fontWeight: '800' },
  secondaryScreen: { flex: 1, paddingHorizontal: 22, paddingTop: 34 },
  receiptsScreen: { flex: 1, paddingHorizontal: 22, paddingTop: 34 },
  receiptsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 22,
  },
  receiptFab: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.accentDark,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.24,
    shadowRadius: 12,
    elevation: 7,
  },
  receiptsContent: { paddingBottom: 34, gap: 12 },
  receiptCard: {
    minHeight: 78,
    borderRadius: 17,
    borderWidth: 0,
    backgroundColor: colors.surface,
    padding: 14,
  },
  receiptCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  receiptCardSummary: {
    minWidth: 0,
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  receiptCardIcon: {
    width: 45,
    height: 45,
    borderRadius: 15,
    backgroundColor: '#F0E6F4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  receiptCardCopy: { flex: 1 },
  receiptCardTitle: { color: colors.ink, fontSize: 14, fontWeight: '800' },
  receiptCardMeta: { color: colors.muted, fontSize: 11, lineHeight: 16, marginTop: 3 },
  receiptActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  viewReceiptButton: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: '#F0E6F4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addReceiptButton: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  receiptDetails: {
    borderTopWidth: 1,
    borderTopColor: colors.line,
    marginTop: 14,
    paddingTop: 14,
    gap: 16,
  },
  receiptItemGroup: { gap: 4 },
  receiptItemGroupHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 4,
  },
  receiptItemGroupTitle: { flex: 1, color: colors.accentDark, fontSize: 13, fontWeight: '800' },
  receiptItemGroupTotal: { color: colors.ink, fontSize: 12, fontWeight: '800' },
  receiptItemRow: {
    minHeight: 43,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingVertical: 6,
  },
  receiptItemCopy: { flex: 1 },
  receiptItemName: { color: colors.ink, fontSize: 12, fontWeight: '600' },
  receiptItemQuantity: { color: colors.muted, fontSize: 10, marginTop: 3 },
  receiptItemAmount: { color: colors.ink, fontSize: 12, fontWeight: '700' },
  receiptNoItems: { color: colors.muted, fontSize: 12, paddingVertical: 4 },
  receiptFinalTotal: {
    borderTopWidth: 1,
    borderTopColor: colors.line,
    paddingTop: 13,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  receiptFinalTotalLabel: { color: colors.ink, fontSize: 14, fontWeight: '800' },
  receiptFinalTotalAmount: { color: colors.accentDark, fontSize: 15, fontWeight: '900' },
  receiptPreviewBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(38, 31, 42, 0.72)',
    padding: 18,
    justifyContent: 'center',
  },
  receiptPreviewCard: {
    height: '82%',
    borderRadius: 24,
    overflow: 'hidden',
    backgroundColor: colors.surface,
  },
  receiptPreviewHeader: {
    minHeight: 64,
    paddingLeft: 20,
    paddingRight: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  receiptPreviewTitle: { flex: 1, color: colors.ink, fontSize: 17, fontWeight: '800' },
  receiptPreviewClose: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: colors.canvas,
    alignItems: 'center',
    justifyContent: 'center',
  },
  receiptPreviewImage: { flex: 1, width: '100%', backgroundColor: '#18151A' },
  receiptPreviewStatus: {
    position: 'absolute',
    top: 64,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: '#18151A',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
  },
  receiptPreviewErrorText: { color: colors.white, fontSize: 14, fontWeight: '700' },
  receiptPreviewUnavailable: {
    flex: 1,
    padding: 30,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
  },
  walletContent: { paddingHorizontal: 22, paddingTop: 34, paddingBottom: 40 },
  walletListHeading: {
    marginTop: 32,
    marginBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  secondaryEyebrow: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.4,
  },
  secondaryTitle: {
    color: colors.ink,
    fontSize: 30,
    fontWeight: '800',
    letterSpacing: -0.7,
    marginTop: 6,
  },
  emptyScreenCard: {
    marginTop: 34,
    backgroundColor: colors.surface,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: 28,
    paddingVertical: 46,
    alignItems: 'center',
  },
  emptyScreenIcon: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: '#F0E6F4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyScreenTitle: { color: colors.ink, fontSize: 19, fontWeight: '800', marginTop: 18 },
  emptyScreenText: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 19,
    textAlign: 'center',
    marginTop: 7,
    maxWidth: 290,
  },
  settingsContent: { paddingBottom: 32 },
  settingsIntro: { color: colors.muted, fontSize: 14, lineHeight: 20, marginTop: 10 },
  settingsSection: { marginTop: 28 },
  settingsLabel: { color: colors.ink, fontSize: 13, fontWeight: '800', marginBottom: 9 },
  settingsSelect: {
    minHeight: 66,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 15,
    backgroundColor: colors.surface,
    paddingHorizontal: 13,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  settingsSelectCopy: { flexDirection: 'row', alignItems: 'center', gap: 11 },
  settingsSelectIcon: {
    width: 40,
    height: 40,
    borderRadius: 13,
    backgroundColor: '#F0E6F4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingsSelectValue: { color: colors.ink, fontSize: 14, fontWeight: '700' },
  settingsSelectHint: { color: colors.muted, fontSize: 11, marginTop: 3 },
  settingsConnection: {
    minHeight: 66,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 15,
    backgroundColor: colors.surface,
    paddingHorizontal: 13,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  settingsConnectionCopy: { flex: 1, marginRight: 10 },
  setupLoading: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.canvas,
  },
  setupScreen: {
    flex: 1,
    backgroundColor: colors.canvas,
    justifyContent: 'center',
    paddingHorizontal: 22,
    paddingVertical: 24,
  },
  setupCard: {
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 26,
    padding: 24,
  },
  setupIcon: {
    width: 54,
    height: 54,
    borderRadius: 18,
    backgroundColor: '#F0E6F4',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
  },
  setupEyebrow: { color: colors.accent, fontSize: 11, fontWeight: '800', letterSpacing: 1.4 },
  setupTitle: {
    color: colors.ink,
    fontSize: 28,
    fontWeight: '800',
    letterSpacing: -0.6,
    marginTop: 6,
  },
  setupIntro: { color: colors.muted, fontSize: 13, lineHeight: 19, marginTop: 9, marginBottom: 22 },
  setupLabel: {
    color: colors.ink,
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 7,
    marginTop: 13,
  },
  setupInput: {
    height: 50,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 14,
    backgroundColor: colors.canvas,
    paddingHorizontal: 14,
    color: colors.ink,
    fontSize: 14,
  },
  setupTokenField: {
    height: 50,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 14,
    backgroundColor: colors.canvas,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
  },
  setupTokenInput: { flex: 1, color: colors.ink, fontSize: 14, marginRight: 10 },
  setupError: { color: '#B42318', fontSize: 12, lineHeight: 17, marginTop: 12 },
  setupRecovery: {
    borderWidth: 1,
    borderColor: '#F2C7C2',
    borderRadius: 13,
    backgroundColor: '#FFF4F2',
    padding: 12,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 9,
    marginBottom: 8,
  },
  setupRecoveryText: { flex: 1, color: '#8A271F', fontSize: 12, lineHeight: 18 },
  setupActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10, marginTop: 24 },
  setupCancel: { minHeight: 48, justifyContent: 'center', paddingHorizontal: 17 },
  setupCancelText: { color: colors.ink, fontSize: 14, fontWeight: '700' },
  setupSave: {
    minHeight: 48,
    borderRadius: 14,
    backgroundColor: colors.accent,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
  },
  setupSaveText: { color: colors.white, fontSize: 14, fontWeight: '800' },
});
