import { Platform, StyleSheet } from 'react-native';

import { colors } from './theme';
import { setupStyles } from './features/setup/setupStyles';

export const styles = StyleSheet.create({
  swipeProvider: { flex: 1 },
  safeArea: { flex: 1, backgroundColor: colors.canvas },
  homeSafeArea: { backgroundColor: 'transparent' },
  appShell: {
    flex: 1,
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
    backgroundColor: colors.canvas,
  },
  ambientBackdrop: { position: 'absolute', inset: 0, overflow: 'hidden' },
  ambientGlowTop: {
    position: 'absolute',
    width: 310,
    height: 310,
    borderRadius: 155,
    top: -110,
    right: -105,
    backgroundColor: 'rgba(202, 174, 225, 0.34)',
  },
  ambientGlowBottom: {
    position: 'absolute',
    width: 360,
    height: 360,
    borderRadius: 180,
    bottom: -180,
    left: -160,
    backgroundColor: 'rgba(165, 213, 220, 0.27)',
  },
  tabContent: { flex: 1, backgroundColor: 'transparent' },
  content: { paddingHorizontal: 22, paddingTop: 24, paddingBottom: 190 },
  swipeContainer: {
    overflow: 'hidden',
    backgroundColor: '#D84A4A',
    borderRadius: 17,
  },
  squareSwipeContainer: { borderRadius: 0 },
  borderedSwipeContainer: { borderWidth: 1, borderColor: colors.line },
  openSwipeContainer: { zIndex: 2 },
  swipeForeground: { backgroundColor: colors.canvas },
  containedSwipeContainer: { backgroundColor: 'transparent' },
  openContainedSwipeContainer: { backgroundColor: '#D84A4A' },
  containedSwipeForeground: { backgroundColor: 'rgba(255, 255, 255, 0.18)' },
  borderedSwipeForeground: { backgroundColor: colors.surface },
  swipeDeleteButton: {
    position: 'absolute',
    top: 0,
    right: 0,
    height: '100%',
    width: 82,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
  },
  swipeRevealSpacer: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    backgroundColor: colors.canvas,
  },
  swipeDeleteText: { color: colors.white, fontSize: 10, fontWeight: '800' },
  deleteConfirmBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(38, 31, 42, 0.55)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 28,
  },
  deleteConfirmCard: {
    width: '100%',
    maxWidth: 380,
    borderRadius: 24,
    backgroundColor: colors.surface,
    padding: 24,
    alignItems: 'center',
  },
  deleteConfirmIcon: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#FBE8E8',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  deleteConfirmTitle: { color: colors.ink, fontSize: 19, fontWeight: '800', textAlign: 'center' },
  deleteConfirmText: { color: colors.muted, fontSize: 13, marginTop: 8 },
  deleteConfirmActions: { flexDirection: 'row', gap: 10, marginTop: 24 },
  deleteCancelButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 14,
    backgroundColor: colors.canvas,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteCancelText: { color: colors.ink, fontSize: 14, fontWeight: '800' },
  deleteConfirmButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 14,
    backgroundColor: '#D84A4A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteConfirmButtonText: { color: colors.white, fontSize: 14, fontWeight: '800' },
  loadingMore: { marginVertical: 22 },
  summaryCard: {
    marginHorizontal: 0,
    marginTop: -8,
    marginBottom: 12,
    padding: 24,
    position: 'relative',
    overflow: 'hidden',
    borderRadius: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.28)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.72)',
  },
  cashFlowEyebrow: {
    color: colors.muted,
    fontSize: 10,
    letterSpacing: 1.2,
    fontWeight: '800',
    textAlign: 'center',
  },
  cashFlowBalance: {
    marginTop: 5,
    color: colors.ink,
    fontSize: 30,
    fontWeight: '800',
    letterSpacing: -0.8,
    textAlign: 'center',
    fontVariant: ['tabular-nums'],
  },
  cashFlowMonth: { marginTop: 1, color: colors.muted, fontSize: 13, textAlign: 'center' },
  cashFlowMetrics: {
    marginTop: 16,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 22,
  },
  cashFlowMetric: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  dot: { width: 9, height: 9, borderRadius: 5, overflow: 'hidden', position: 'relative' },
  incomeDot: { backgroundColor: 'rgba(74, 190, 136, 0.72)' },
  spentDot: { backgroundColor: 'rgba(225, 104, 126, 0.72)' },
  cashFlowMetricLabel: { color: colors.muted, fontSize: 11 },
  cashFlowMetricValue: {
    color: colors.ink,
    fontSize: 11,
    fontWeight: '700',
    fontVariant: ['tabular-nums'],
  },
  cashFlowChart: {
    height: 102,
    marginTop: 15,
    paddingTop: 4,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-around',
  },
  cashFlowColumn: { flex: 1, alignItems: 'center' },
  cashFlowBars: { height: 76, flexDirection: 'row', alignItems: 'flex-end', gap: 3 },
  cashFlowBar: { width: 11, borderRadius: 5, overflow: 'hidden', position: 'relative' },
  cashFlowIncomeBar: { backgroundColor: 'rgba(74, 190, 136, 0.72)' },
  cashFlowExpenseBar: { backgroundColor: 'rgba(225, 104, 126, 0.72)' },
  cashFlowChartLabel: { height: 20, paddingTop: 4, color: colors.muted, fontSize: 10 },
  queuePanel: {
    borderWidth: 1,
    borderColor: '#D8C4E1',
    borderRadius: 18,
    backgroundColor: '#F8F2FA',
    padding: 15,
    marginBottom: 24,
  },
  queueHeading: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  queueHeadingCopy: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  queueStatusDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.accent },
  queueTitle: { color: colors.ink, fontSize: 15, fontWeight: '800' },
  queueCount: {
    minWidth: 25,
    height: 25,
    borderRadius: 13,
    backgroundColor: '#EADCF0',
    color: colors.accentDark,
    textAlign: 'center',
    lineHeight: 25,
    fontSize: 12,
    fontWeight: '800',
  },
  queueIntro: { color: colors.muted, fontSize: 11, lineHeight: 16, marginTop: 6 },
  queueItem: {
    flexDirection: 'row',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#E5D7EA',
    marginTop: 13,
    paddingTop: 13,
  },
  queueItemIcon: {
    width: 38,
    height: 38,
    borderRadius: 13,
    backgroundColor: '#EADCF0',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  queueItemCopy: { flex: 1 },
  queueItemTitle: { color: colors.ink, fontSize: 13, fontWeight: '800' },
  queueItemMeta: { color: colors.muted, fontSize: 11, marginTop: 2 },
  queueItemError: { color: colors.accentDark, fontSize: 10, lineHeight: 15, marginTop: 5 },
  queueItemAction: { alignItems: 'flex-end', marginLeft: 8 },
  queueItemAmount: { color: colors.ink, fontSize: 12, fontWeight: '800' },
  retryQueueButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    minHeight: 28,
    paddingHorizontal: 8,
    marginTop: 4,
    borderRadius: 8,
    backgroundColor: colors.white,
  },
  retryQueueText: { color: colors.accent, fontSize: 11, fontWeight: '800' },
  discardQueueButton: { minHeight: 24, justifyContent: 'center', marginTop: 2 },
  discardQueueText: { color: colors.muted, fontSize: 10, fontWeight: '700' },
  transactionRow: {
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    paddingVertical: 9,
    paddingHorizontal: 12,
    position: 'relative',
  },
  containedTransactionRow: { backgroundColor: 'transparent' },
  dailyTransactionGroup: {
    position: 'relative',
    overflow: 'hidden',
    borderRadius: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.82)',
    paddingVertical: 6,
    marginBottom: 0,
  },
  transactionGlassGroup: { overflow: 'hidden' },
  transactionGlassGroupFirst: { borderTopLeftRadius: 18, borderTopRightRadius: 18 },
  transactionGlassGroupLast: { borderBottomLeftRadius: 18, borderBottomRightRadius: 18 },
  splitTransactionGroup: {
    overflow: 'hidden',
  },
  splitTransactionParent: {
    borderWidth: 0,
  },
  transactionSplitPill: {
    height: 18,
    paddingHorizontal: 6,
    borderRadius: 9,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: '#EEE6F2',
  },
  transactionSplitPillText: { color: colors.accentDark, fontSize: 9, fontWeight: '800' },
  splitTransactionChild: {
    minHeight: 44,
    paddingLeft: 21,
    paddingRight: 12,
    paddingVertical: 4,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },
  splitTransactionChildIcon: {
    width: 30,
    height: 30,
    marginRight: 11,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  splitTransactionChildTitle: { color: colors.ink, fontSize: 12, fontWeight: '700' },
  splitTransactionChildMeta: { gap: 3, marginTop: 1 },
  splitTransactionChildAmount: { fontSize: 12, opacity: 0.68 },
  transactionIcon: {
    width: 39,
    height: 39,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 11,
  },
  expenseIcon: { backgroundColor: '#EFE5F3' },
  incomeIcon: { backgroundColor: '#DDF0E5' },
  transactionCopy: { flex: 1 },
  merchant: { color: colors.ink, fontSize: 14, fontWeight: '700' },
  transactionMeta: { color: colors.muted, fontSize: 11, marginTop: 2 },
  transactionMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minWidth: 0,
    marginTop: 2,
    gap: 4,
    overflow: 'hidden',
  },
  transactionMetaDetails: {
    flex: 1,
    minWidth: 0,
  },
  transactionDetailsSplitList: { marginTop: 8, gap: 8 },
  transactionDetailsSplitRow: {
    minHeight: 46,
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 12,
    backgroundColor: colors.canvas,
  },
  transactionDetailsSplitTitle: { color: colors.ink, fontSize: 13, fontWeight: '700' },
  transactionDetailsSplitAmount: {
    marginLeft: 12,
    color: colors.ink,
    fontSize: 12,
    fontWeight: '800',
    fontVariant: ['tabular-nums'],
  },
  transactionTagPill: {
    flexShrink: 1,
    maxWidth: 82,
    height: 18,
    paddingHorizontal: 6,
    borderRadius: 9,
    backgroundColor: '#EEE6F2',
    justifyContent: 'center',
  },
  transactionTagText: { color: colors.accentDark, fontSize: 9, fontWeight: '700' },
  transactionWalletPill: {
    height: 18,
    paddingHorizontal: 6,
    borderRadius: 9,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  transactionClearedPill: {
    height: 18,
    minWidth: 22,
    paddingHorizontal: 5,
    borderRadius: 9,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E2F4E8',
  },
  dateSectionHeader: {
    alignSelf: 'stretch',
    marginHorizontal: -22,
    marginTop: 0,
    marginBottom: 5,
    paddingLeft: 22,
    paddingRight: 34,
    paddingTop: 24,
    paddingBottom: 7,
    position: 'relative',
    backgroundColor: '#F5F3F6',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  elevatedDateSectionHeaderOverlay: {
    position: 'absolute',
    inset: 0,
    backgroundColor: 'transparent',
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.09,
    shadowRadius: 8,
    elevation: 3,
  },
  dateSectionHeaderFlushTop: { marginTop: 0 },
  stickyDateSectionHeader: { marginBottom: 0 },
  glassDateSectionHeader: { backgroundColor: 'transparent', paddingBottom: 12 },
  fixedDateSectionHeaderContainer: {
    position: 'absolute',
    top: 0,
    left: 22,
    right: 22,
    zIndex: 20,
  },
  topStatusFade: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 15,
    experimental_backgroundImage:
      'linear-gradient(180deg, rgba(245, 243, 246, 0.82) 0%, rgba(245, 243, 246, 0.38) 58%, rgba(245, 243, 246, 0) 100%)',
  },
  dateSectionHeaderContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  stickyDateGlassTopMask: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 2,
    backgroundColor: 'transparent',
  },
  transactionSectionSpacing: { height: 8 },
  dateSectionTitle: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '800',
  },
  dateSectionAmount: {
    color: colors.muted,
    marginLeft: 0,
  },
  amount: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '700',
    fontVariant: ['tabular-nums'],
    marginLeft: 16,
  },
  incomeAmount: { color: colors.green },
  separator: { height: 0 },
  fab: {
    width: 62,
    height: 62,
    borderRadius: 31,
    backgroundColor: 'rgba(119, 64, 154, 0.72)',
    overflow: 'hidden',
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.accentDark,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 13,
    elevation: 9,
  },
  homeActionGroup: {
    position: 'absolute',
    right: 24,
    bottom: Platform.OS === 'ios' ? 102 : 90,
    zIndex: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  homeCameraFab: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: 'rgba(255, 255, 255, 0.58)',
    overflow: 'hidden',
    position: 'relative',
    borderWidth: 1,
    borderColor: '#E1D6E7',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.14,
    shadowRadius: 10,
    elevation: 6,
  },
  homeCameraFabPressed: { transform: [{ scale: 0.96 }], backgroundColor: '#F5EFF7' },
  homeReceiptError: {
    position: 'absolute',
    right: 24,
    bottom: Platform.OS === 'ios' ? 166 : 154,
    maxWidth: 290,
    paddingHorizontal: 13,
    paddingVertical: 9,
    borderRadius: 11,
    backgroundColor: '#FFF1F1',
    borderWidth: 1,
    borderColor: '#F2CCCC',
  },
  homeReceiptErrorText: { color: '#9E3535', fontSize: 11, fontWeight: '700' },
  fabPressed: { transform: [{ scale: 0.96 }], backgroundColor: colors.accentDark },
  state: { flex: 1, padding: 32, alignItems: 'center', justifyContent: 'center' },
  stateTitle: { color: colors.ink, fontSize: 20, fontWeight: '700', marginTop: 16 },
  stateText: { color: colors.muted, textAlign: 'center', lineHeight: 20, marginTop: 9 },
  retryButton: {
    backgroundColor: colors.ink,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
    marginTop: 20,
  },
  retryText: { color: colors.white, fontWeight: '700' },
  inlineError: { backgroundColor: '#F0E6F4', borderRadius: 12, padding: 12, marginBottom: 18 },
  inlineErrorText: { color: colors.accentDark, fontSize: 12 },
  emptyText: { color: colors.muted, textAlign: 'center', padding: 40 },
  modalRoot: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'transparent',
  },
  scrim: {
    position: 'absolute',
    top: 0,
    right: 0,
    left: 0,
    height: '16%',
    backgroundColor: colors.overlay,
  },
  sheet: {
    backgroundColor: 'transparent',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    overflow: 'hidden',
    height: '92%',
    paddingHorizontal: 22,
    paddingBottom: Platform.OS === 'ios' ? 28 : 22,
  },
  handle: {
    width: 42,
    height: 5,
    backgroundColor: '#D3CEC4',
    borderRadius: 4,
    alignSelf: 'center',
    marginTop: 10,
    marginBottom: 17,
  },
  sheetHeading: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  sheetTitleGroup: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  sheetTitleIcon: {
    width: 38,
    height: 38,
    borderRadius: 13,
    backgroundColor: '#F0E6F4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetTitle: { color: colors.ink, fontSize: 22, fontWeight: '800', letterSpacing: -0.4 },
  sheetHeadingActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  closeButton: {
    width: 39,
    height: 39,
    borderRadius: 20,
    backgroundColor: colors.canvas,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modeToggle: {
    backgroundColor: colors.canvas,
    borderRadius: 12,
    padding: 3,
    flexDirection: 'row',
    gap: 2,
  },
  modeButton: {
    width: 38,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
  },
  activeModeButton: { backgroundColor: colors.accent },
  amountDirectionRow: { width: '100%', flexDirection: 'row', alignItems: 'flex-end', gap: 10 },
  amountFieldColumn: { flex: 1, minWidth: 0 },
  directionToggle: {
    width: 108,
    height: 50,
    flexDirection: 'row',
    gap: 2,
    marginBottom: 14,
    padding: 4,
    borderRadius: 14,
    backgroundColor: colors.canvas,
  },
  directionButton: {
    flex: 1,
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 11,
  },
  activeExpenseDirectionButton: { backgroundColor: '#C94B4B' },
  activeIncomeDirectionButton: { backgroundColor: colors.green },
  form: { paddingBottom: 12 },
  numberKeyboardAccessory: {
    minHeight: 45,
    paddingHorizontal: 16,
    backgroundColor: 'rgba(250, 248, 251, 0.96)',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.line,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  numberKeyboardDoneButton: { paddingHorizontal: 8, paddingVertical: 6 },
  numberKeyboardDoneText: { color: colors.accentDark, fontSize: 16, fontWeight: '700' },
  fieldGroup: {
    marginBottom: 14,
  },
  fieldControl: { width: '100%' },
  choiceControl: { width: '100%', flexDirection: 'row', alignItems: 'center', gap: 9 },
  choiceScroller: { flex: 1 },
  choiceRow: { gap: 9, paddingRight: 10 },
  choice: {
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.white,
    paddingHorizontal: 15,
    minHeight: 40,
    justifyContent: 'center',
    borderRadius: 20,
  },
  activeChoice: { borderColor: colors.accent, backgroundColor: '#F0E6F4' },
  choiceText: { color: colors.muted, fontSize: 14, fontWeight: '600' },
  activeChoiceText: { color: colors.accentDark },
  tagSearchButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tagSearchSheet: {
    height: '68%',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    backgroundColor: 'transparent',
    overflow: 'hidden',
    paddingHorizontal: 18,
    paddingBottom: Platform.OS === 'ios' ? 28 : 18,
  },
  tagSearchHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  tagSearchField: {
    height: 52,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.canvas,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  tagSearchList: { gap: 10, paddingTop: 16, paddingBottom: 24 },
  tagSearchOption: {
    minHeight: 52,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  activeTagSearchOption: { borderColor: colors.accent, backgroundColor: '#FAF5FC' },
  tagCheckbox: {
    width: 24,
    height: 24,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.line,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeTagCheckbox: { borderColor: colors.accent, backgroundColor: colors.accent },
  tagSearchOptionText: { color: colors.ink, fontSize: 14, fontWeight: '700' },
  categoryField: {
    width: '100%',
    height: 50,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 14,
    backgroundColor: colors.white,
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  categoryFieldPressed: { backgroundColor: '#FAF8FB' },
  categoryFieldSelection: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 },
  categoryFieldIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F2EEF4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryFieldText: { color: colors.ink, fontSize: 14, fontWeight: '700' },
  categoryPlaceholder: { color: '#A7A0AA', fontSize: 14 },
  nestedModalRoot: { flex: 1, justifyContent: 'flex-end' },
  nestedScrim: {
    position: 'absolute',
    inset: 0,
    backgroundColor: 'rgba(42, 29, 48, 0.58)',
  },
  categorySheet: {
    height: '66%',
    backgroundColor: 'transparent',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 18,
    paddingBottom: Platform.OS === 'ios' ? 28 : 18,
    shadowColor: '#2A1D30',
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.18,
    shadowRadius: 24,
    elevation: 18,
    overflow: 'hidden',
  },
  categorySheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    marginBottom: 18,
  },
  categorySheetTitle: { color: colors.ink, fontSize: 22, fontWeight: '800' },
  categorySheetSubtitle: { color: colors.muted, fontSize: 12, marginTop: 4 },
  categoryGrid: { paddingBottom: 22 },
  categoryGridRow: { alignItems: 'flex-start' },
  categoryTile: { width: '33.333%', alignItems: 'center', paddingHorizontal: 5, marginBottom: 20 },
  categoryTileIcon: {
    width: 66,
    height: 66,
    borderRadius: 33,
    backgroundColor: '#F3F5F6',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  activeCategoryTileIcon: { borderColor: colors.accent, backgroundColor: '#F0E6F4' },
  categoryCheckBadge: {
    position: 'absolute',
    right: -2,
    top: -2,
    width: 21,
    height: 21,
    borderRadius: 11,
    backgroundColor: colors.accent,
    borderWidth: 2,
    borderColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryTileText: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 16,
    textAlign: 'center',
    marginTop: 8,
  },
  activeCategoryTileText: { color: colors.accentDark, fontWeight: '700' },
  categoryEmpty: { color: colors.muted, textAlign: 'center', paddingVertical: 40 },
  accountSheet: {
    height: '62%',
    backgroundColor: 'transparent',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 20,
    overflow: 'hidden',
  },
  accountOptionsScroll: { flex: 1 },
  accountOptions: {
    gap: 11,
    paddingTop: 20,
    paddingBottom: Platform.OS === 'ios' ? 28 : 18,
  },
  accountOption: {
    minHeight: 62,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
  },
  activeAccountOption: { borderColor: colors.accent, backgroundColor: '#F0E6F4' },
  accountOptionIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F2EEF4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  accountOptionText: { flex: 1, color: colors.ink, fontSize: 14, fontWeight: '600' },
  activeAccountOptionText: { color: colors.accentDark, fontWeight: '700' },
  field: {
    width: '100%',
    height: 50,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 13,
    backgroundColor: colors.white,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    gap: 11,
  },
  multilineField: { height: 80, alignItems: 'flex-start', paddingTop: 15 },
  input: { flex: 1, color: colors.ink, fontSize: 15, outlineStyle: 'none' } as never,
  multilineInput: { minHeight: 50, textAlignVertical: 'top' },
  dateShortcuts: { width: '100%' },
  dateCalendarButton: {
    minHeight: 48,
    width: '100%',
    minWidth: 0,
    paddingHorizontal: 13,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 9,
  },
  dateCalendarText: { color: colors.ink, fontSize: 14, fontWeight: '700' },
  webDateInput: { justifyContent: 'flex-start' },
  webDateTextInput: {
    flex: 1,
    color: colors.ink,
    fontSize: 14,
    fontWeight: '700',
    outlineStyle: 'none',
  } as never,
  datePickerSheet: {
    width: '100%',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    backgroundColor: 'transparent',
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: Platform.OS === 'ios' ? 34 : 24,
    overflow: 'hidden',
  },
  datePickerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  datePickerSelection: { color: colors.muted, fontSize: 13, fontWeight: '600', marginTop: 3 },
  dateDoneButton: {
    minHeight: 38,
    paddingHorizontal: 15,
    borderRadius: 12,
    backgroundColor: '#F0E6F4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dateDoneText: { color: colors.accentDark, fontSize: 13, fontWeight: '800' },
  datePicker: {
    width: '89%',
    alignSelf: 'center',
    marginVertical: 17,
    transform: [{ scale: 1.12 }],
  },
  splitCard: {
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 16,
    padding: 15,
    marginBottom: 16,
    backgroundColor: '#FAF8FB',
  },
  splitTitle: { color: colors.ink, fontWeight: '700', marginBottom: 14 },
  expenseSplitRow: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 14,
    backgroundColor: '#FAF8FB',
    gap: 10,
    marginBottom: 16,
  },
  expenseSplitToggle: {
    flex: 1,
    minWidth: 0,
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
  },
  expenseSplitCheckbox: {
    width: 22,
    height: 22,
    borderWidth: 2,
    borderColor: colors.muted,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  expenseSplitCheckboxChecked: { borderColor: colors.accent, backgroundColor: colors.accent },
  expenseSplitToggleTitle: { color: colors.ink, fontSize: 13, fontWeight: '800' },
  expenseSplitPickerButton: {
    width: '48%',
    height: 42,
    paddingHorizontal: 11,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 11,
    backgroundColor: colors.white,
  },
  expenseSplitPickerDisabled: { opacity: 0.45 },
  expenseSplitPickerText: { flex: 1, color: colors.ink, fontSize: 12, fontWeight: '700' },
  expenseSplitSheet: {
    width: '100%',
    maxHeight: '70%',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    backgroundColor: 'transparent',
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: Platform.OS === 'ios' ? 34 : 24,
    overflow: 'hidden',
  },
  expenseSplitList: { gap: 8, paddingBottom: 8 },
  expenseSplitOption: {
    minHeight: 66,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 13,
    paddingVertical: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.white,
  },
  expenseSplitOptionActive: { borderColor: colors.accent, backgroundColor: '#FAF4FC' },
  expenseSplitOptionIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F0E6F4',
    marginRight: 11,
  },
  expenseSplitOptionCopy: { flex: 1, minWidth: 0 },
  expenseSplitOptionTitle: { color: colors.ink, fontSize: 14, fontWeight: '800' },
  expenseSplitOptionDetail: { color: colors.muted, fontSize: 11, marginTop: 3 },
  expenseSplitFields: { gap: 12 },
  errorText: {
    color: colors.accentDark,
    fontSize: 12,
    lineHeight: 18,
    marginBottom: 12,
    backgroundColor: '#F8EFFA',
    borderRadius: 10,
    padding: 10,
  },
  sheetActions: {
    borderTopWidth: 1,
    borderTopColor: colors.line,
    paddingTop: 15,
    flexDirection: 'row',
    gap: 12,
  },
  transactionEditAction: { flex: 1, minWidth: 0 },
  transactionDetailsActions: {
    width: '100%',
    paddingHorizontal: 0,
    marginTop: 24,
    paddingTop: 0,
    borderTopWidth: 0,
  },
  transactionDeleteConfirmOverlay: {
    position: 'absolute',
    inset: 0,
    zIndex: 40,
    backgroundColor: 'rgba(38, 31, 42, 0.34)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 28,
  },
  liquidDeleteConfirmCard: {
    overflow: 'hidden',
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.78)',
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.2,
    shadowRadius: 26,
    elevation: 12,
  },
  transactionConfirmAction: { flex: 1 },
  cancelButton: {
    minHeight: 49,
    paddingHorizontal: 22,
    borderRadius: 14,
    backgroundColor: colors.canvas,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelText: { color: colors.ink, fontWeight: '700', fontSize: 14 },
  saveButton: {
    flex: 1,
    minHeight: 49,
    borderRadius: 14,
    backgroundColor: colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  disabledButton: { opacity: 0.42 },
  saveText: { color: colors.white, fontWeight: '700', fontSize: 14 },
  routerTabs: { flex: 1 },
  routerTabSlot: { flex: 1, minHeight: 0, overflow: 'hidden' },
  bottomNavigation: {
    minHeight: 76,
    borderTopWidth: 1,
    borderTopColor: colors.line,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    flexDirection: 'row',
    paddingHorizontal: 12,
    paddingTop: 8,
  },
  bottomTab: { flex: 1, alignItems: 'center', justifyContent: 'flex-start', gap: 3 },
  bottomTabIcon: {
    width: 42,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  receiptBadge: {
    position: 'absolute',
    top: -5,
    right: -5,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    paddingHorizontal: 5,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.accent,
    borderWidth: 2,
    borderColor: colors.surface,
  },
  bottomTabText: { color: colors.muted, fontSize: 11, fontWeight: '600' },
  secondaryFixedScreen: { flex: 1, paddingTop: 34, backgroundColor: 'transparent' },
  accountScreen: { flex: 1, backgroundColor: 'transparent' },
  moreScreen: { flex: 1, paddingTop: 34, backgroundColor: 'transparent' },
  moreDetailPage: { flex: 1, backgroundColor: 'transparent' },
  moreTransitionStack: { flex: 1, overflow: 'hidden' },
  moreSlidingPage: {
    position: 'absolute',
    inset: 0,
    backgroundColor: colors.canvas,
  },
  moreMenu: { paddingHorizontal: 16, paddingTop: 14, gap: 10 },
  moreMenuItem: {
    minHeight: 70,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.78)',
    borderRadius: 22,
    backgroundColor: 'transparent',
    overflow: 'hidden',
  },
  moreMenuIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F0E7F5',
  },
  moreMenuBadge: {
    position: 'absolute',
    top: -4,
    right: -5,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    paddingHorizontal: 4,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.accent,
    borderWidth: 2,
    borderColor: colors.canvas,
  },
  receiptBadgeText: { color: colors.white, fontSize: 9, fontWeight: '800' },
  moreMenuTitle: { color: colors.ink, fontSize: 15, fontWeight: '800' },
  moreMenuDescription: { marginTop: 3, color: colors.muted, fontSize: 11 },
  nestedHeaderContent: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  nestedBackButton: {
    width: 34,
    height: 42,
    marginLeft: -8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryHeader: {
    marginTop: -34,
    paddingTop: 34,
    paddingHorizontal: 22,
    paddingBottom: 12,
    position: 'relative',
    backgroundColor: 'transparent',
  },
  accountStickyHeader: {
    position: 'absolute',
    left: 22,
    right: 22,
    zIndex: 20,
    padding: 24,
    overflow: 'hidden',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.72)',
    backgroundColor: 'transparent',
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 4,
  },
  headerAccountDropdown: { marginTop: 4 },
  headerAccountSelect: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    maxWidth: '100%',
    gap: 7,
  },
  headerAccountValue: {
    flexShrink: 1,
    color: colors.ink,
    fontSize: 30,
    fontWeight: '800',
    letterSpacing: -0.7,
  },
  accountHeaderMetrics: {
    flexDirection: 'row',
    alignItems: 'stretch',
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: colors.line,
  },
  accountHeaderMetric: { flex: 1, minWidth: 0 },
  accountHeaderMetricDivider: {
    width: 1,
    marginHorizontal: 14,
    backgroundColor: colors.line,
  },
  accountHeaderMetricLabel: {
    color: colors.muted,
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 0.8,
  },
  accountHeaderMetricValue: {
    marginTop: 4,
    color: colors.ink,
    fontSize: 17,
    fontWeight: '800',
    fontVariant: ['tabular-nums'],
  },
  receiptsScreen: { flex: 1, paddingTop: 34 },
  sharedExpensesScreen: { flex: 1, paddingTop: 34, backgroundColor: 'transparent' },
  sharedExpensesList: { paddingHorizontal: 22, paddingVertical: 12, flexGrow: 1 },
  sharedExpenseRow: {
    minHeight: 68,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginBottom: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.7)',
    backgroundColor: 'transparent',
    overflow: 'hidden',
  },
  sharedExpenseIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F0E7F5',
  },
  sharedExpenseAmounts: { alignItems: 'flex-end', marginLeft: 10 },
  sharedExpenseBalance: { marginTop: 3, color: colors.muted, fontSize: 10, fontWeight: '700' },
  sharedExpenseDetailList: { paddingHorizontal: 18, paddingBottom: 24 },
  sharedExpenseSummary: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    paddingVertical: 18,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  sharedExpenseDetailRow: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  receiptsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: -34,
    marginBottom: 0,
    paddingTop: 34,
    paddingHorizontal: 22,
    paddingBottom: 12,
    position: 'relative',
    backgroundColor: 'transparent',
  },
  receiptsError: { marginHorizontal: 22 },
  receiptsContent: { paddingHorizontal: 22, paddingBottom: 34, alignItems: 'stretch' },
  receiptCard: {
    minHeight: 56,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.7)',
    backgroundColor: 'transparent',
    paddingVertical: 10,
    paddingHorizontal: 12,
    overflow: 'hidden',
  },
  receiptCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
  },
  receiptCardSummary: {
    minWidth: 0,
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
  },
  receiptCardIcon: {
    width: 39,
    height: 39,
    borderRadius: 13,
    backgroundColor: '#F0E6F4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  receiptCardCopy: { flex: 1 },
  receiptCardTitle: { color: colors.ink, fontSize: 14, fontWeight: '700' },
  receiptCardMetaRow: {
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginTop: 2,
  },
  receiptCardMeta: { flexShrink: 1, color: colors.muted, fontSize: 11, lineHeight: 16 },
  receiptSubmittedPill: {
    height: 18,
    minWidth: 22,
    paddingHorizontal: 5,
    borderRadius: 9,
    backgroundColor: '#E2F4E8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  receiptDetails: {
    borderTopWidth: 1,
    borderTopColor: colors.line,
    marginTop: 14,
    paddingTop: 14,
    gap: 16,
  },
  receiptDetailsModalRoot: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  receiptDetailsScrim: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: colors.overlay,
  },
  receiptDetailsSheet: {
    maxHeight: '82%',
    minHeight: 280,
    paddingHorizontal: 22,
    paddingBottom: Platform.OS === 'ios' ? 28 : 22,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: 'transparent',
    overflow: 'hidden',
  },
  receiptDetailsHeading: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 18,
  },
  receiptDetailsTitle: {
    flexShrink: 1,
    color: colors.ink,
    fontSize: 20,
    fontWeight: '800',
  },
  receiptDetailsActions: { flexDirection: 'row', gap: 10, marginBottom: 20 },
  receiptDetailsSecondaryAction: {
    flex: 1,
    minHeight: 46,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  receiptDetailsSecondaryActionText: { color: colors.accentDark, fontWeight: '800' },
  receiptDetailsPrimaryAction: {
    flex: 1,
    minHeight: 46,
    borderRadius: 14,
    backgroundColor: colors.accent,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  receiptDetailsPrimaryActionText: { color: colors.white, fontWeight: '800' },
  receiptDetailsSubmitted: {
    flex: 1,
    minHeight: 46,
    borderRadius: 14,
    backgroundColor: colors.canvas,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  receiptDetailsSubmittedText: { color: colors.green, fontWeight: '800' },
  receiptDetailsSheetContent: { gap: 16, paddingBottom: 8 },
  transactionDetailsAmount: {
    color: colors.ink,
    fontSize: 25,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
    marginBottom: 20,
  },
  transactionDetailsHeading: { minHeight: 42, alignItems: 'center' },
  transactionDetailsTitleGroup: { height: 42, flex: 1, minWidth: 0 },
  transactionDetailsContent: { gap: 0, paddingBottom: 8 },
  transactionDetailsCard: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.84)',
    backgroundColor: 'rgba(255, 255, 255, 0.88)',
    overflow: 'hidden',
  },
  transactionDetailsRow: {
    minHeight: 47,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 18,
    paddingHorizontal: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(45, 38, 49, 0.08)',
  },
  transactionDetailsFirstRow: { borderTopWidth: 0 },
  transactionDetailsCardAmount: { fontSize: 15, fontWeight: '900' },
  transactionDetailsLabel: { color: colors.muted, fontSize: 12, fontWeight: '700' },
  transactionDetailsValue: {
    flex: 1,
    color: colors.ink,
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'right',
  },
  transactionDetailsSection: {
    gap: 8,
    paddingHorizontal: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(45, 38, 49, 0.08)',
    paddingVertical: 13,
  },
  transactionDetailsTags: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  transactionDetailsNotes: { color: colors.ink, fontSize: 13, lineHeight: 19 },
  receiptItemGroup: { gap: 4 },
  receiptItemGroupHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 4,
  },
  receiptItemGroupTitle: { flex: 1, color: colors.accentDark, fontSize: 13, fontWeight: '800' },
  receiptItemGroupTotal: { color: colors.ink, fontSize: 12, fontWeight: '800' },
  receiptItemRow: {
    minHeight: 43,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingVertical: 6,
  },
  receiptItemCopy: { flex: 1 },
  receiptItemName: { color: colors.ink, fontSize: 12, fontWeight: '600' },
  receiptItemQuantity: { color: colors.muted, fontSize: 10, marginTop: 3 },
  receiptItemAmount: { color: colors.ink, fontSize: 12, fontWeight: '700' },
  receiptNoItems: { color: colors.muted, fontSize: 12, paddingVertical: 4 },
  receiptFinalTotal: {
    borderTopWidth: 1,
    borderTopColor: colors.line,
    paddingTop: 13,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  receiptFinalTotalLabel: { color: colors.ink, fontSize: 14, fontWeight: '800' },
  receiptFinalTotalAmount: { color: colors.accentDark, fontSize: 15, fontWeight: '900' },
  receiptPreviewBackdrop: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  receiptPreviewScrim: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: colors.overlay,
  },
  receiptPreviewCard: {
    height: '88%',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    overflow: 'hidden',
    backgroundColor: 'transparent',
  },
  receiptPreviewHeader: {
    minHeight: 58,
    paddingLeft: 20,
    paddingRight: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  receiptPreviewTitle: { flex: 1, color: colors.ink, fontSize: 17, fontWeight: '800' },
  receiptPreviewClose: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: colors.canvas,
    alignItems: 'center',
    justifyContent: 'center',
  },
  receiptPreviewImage: { flex: 1, width: '100%', backgroundColor: '#18151A' },
  receiptPreviewStatus: {
    position: 'absolute',
    top: 90,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: '#18151A',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
  },
  receiptPreviewErrorText: { color: colors.white, fontSize: 14, fontWeight: '700' },
  receiptPreviewUnavailable: {
    flex: 1,
    padding: 30,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
  },
  walletContent: { paddingHorizontal: 22, paddingBottom: 40 },
  secondaryEyebrow: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.4,
  },
  secondaryTitle: {
    color: colors.ink,
    fontSize: 30,
    fontWeight: '800',
    letterSpacing: -0.7,
    marginTop: 6,
  },
  emptyScreenCard: {
    marginTop: 34,
    backgroundColor: colors.surface,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: 28,
    paddingVertical: 46,
    alignItems: 'center',
  },
  emptyScreenIcon: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: '#F0E6F4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyScreenTitle: { color: colors.ink, fontSize: 19, fontWeight: '800', marginTop: 18 },
  emptyScreenText: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 19,
    textAlign: 'center',
    marginTop: 7,
    maxWidth: 290,
  },
  settingsContent: { paddingHorizontal: 22, paddingBottom: 32 },
  settingsIntro: { color: colors.muted, fontSize: 14, lineHeight: 20, marginTop: 10 },
  settingsSection: { marginTop: 18 },
  glassContentCard: {
    padding: 14,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.72)',
    backgroundColor: 'transparent',
    overflow: 'hidden',
  },
  settingsLabel: { color: colors.ink, fontSize: 13, fontWeight: '800', marginBottom: 9 },
  settingsSelect: {
    minHeight: 66,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 15,
    backgroundColor: 'transparent',
    paddingHorizontal: 13,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  settingsSelectCopy: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 11 },
  settingsSelectIcon: {
    width: 40,
    height: 40,
    borderRadius: 13,
    backgroundColor: '#F0E6F4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingsSelectValue: { color: colors.ink, fontSize: 14, fontWeight: '700' },
  settingsSelectHint: { color: colors.muted, fontSize: 11, marginTop: 3 },
  settingsConnection: {
    minHeight: 66,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 15,
    backgroundColor: 'transparent',
    paddingHorizontal: 13,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  settingsConnectionCopy: { flex: 1, marginRight: 10 },
  ...setupStyles,
});
